InsightSoftwareConsortium/itk-viewer-bootstrap-ui

src/App.scss
src/Images/GradientOpacitySlider.jsx
src/Images/SampleDistanceSlider.jsx
src/Images/ShadowToggle.jsx
src/style.css

React.memo is preventing the button to be unchecked.
Optimization should probably be done in the parent level.
Co-authored-by:Paul Elliott <paul.elliott@kitware.com>

feat(ShadowToggle): Delete React.memo and select necessary state

---

.eslintrc.js
package-lock.json
package.json

Adds eslint and `npm run lint` command

chore(eslint): add eslint and npm run lint

---

.eslintrc.js
package-lock.json
package.json

We will learn much with these rules.  And pull out our hair due to them.

chore(linting): add eslint-plugin-react-hooks rules

---

src/AppToolbar.jsx
src/style.css

Needs improvement: 
- Unnecessary gap on top of the page

feat(AppToolbar): Translate from MUI to bootstrap

---

docs/.readthedocs.yaml

feat(ReadTheDocs): Configure build pull request build preview

---

index.html

feat(itk-vtk-viewer): Bump version to latest v14

---

src/Main/MainInterface.jsx
src/PointSetInterface.jsx
src/createInterface.jsx

closes #72
The referenceUI parents the point set elements to `context.uiContainer`
A test index.html for point sets
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<link rel="icon" type="image/svg+xml" href="/src/favicon.svg" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Custom itk-viewer Boostrap UI Demo</title>
</head>
<body>
<div
class="content"
style="
position: absolute;
width: 100vw;
height: 100vh;
top: 0;
left: 0;
overflow: hidden;
background: black;
margin: 0;
padding: 0;
"
></div>
<script
type="text/javascript"
src="https://unpkg.com/@babel/polyfill@7.0.0/dist/polyfill.js"
></script>
<script type="text/javascript" src="https://unpkg.com/vtk.js"></script>
<script
type="text/javascript" …
```

fix(point-sets): give referenceUI a good place to parent point set ui

---

src/Images/ColorRangeInput.jsx
src/Images/TransferFunctionWidget.jsx

Fixes bug introduced in 2505e4634662f86f76377d3edb525441c76e9350.

fix(ColorRangeInput): Support images with multiple color channels

---

docs/RTDContents/Contribute/contribute.md
docs/RTDContents/UserGuide/user_guide.md
docs/index.md

- Add info on how o check RTD locally;
- Add example on how to test 3D image with multiple color channels;
- Removes App from the toctree.

DOCS: Add info to Contribute, UserGuide; fix toctree

---

src/Images/ColorRangeInput.jsx

fix(ColorRangeInput): Enable labelImage input by itself

---

package-lock.json
package.json
src/Images/ColorRangeInput.jsx
src/Images/ScaleSelector.jsx

Also bump TransferFunctionEditor version

State context rename: renderedScale to loadedScale/targetScale

---

index.html

Index.html can document the last tested compatible itk-vtk-viewer version.  Will help with keeping itkwidgets in sync: https://github.com/InsightSoftwareConsortium/itkwidgets/pull/523
Non major version triggering changes to itk-vtk-viewer may break this UI code.  Stuff like changing variable names on the XState context.

Pin full itk-vtk-viewer version

---

index.html
src/Main/CroppingPlanesReset.jsx
src/Main/CroppingPlanesToggle.jsx
src/Main/MainInterface.jsx

feat(MainInterface): add cropping plane buttons

---

src/App.jsx
src/Panel.jsx
src/style.css

fix(slice-sliders): float to higher z-index than CornerAnnotation

---

package-lock.json
package.json
src/style.css

feat(tf-editor): bump version for log scale

fix(style): make sidebar vertical scroll bar clickable

---

public/compareTest.html
public/index.html
src/Images/ColorRangeInput.jsx
src/Images/ComponentSelector.jsx
src/Images/ImagesInterface.jsx
src/Layers/CompareControls.jsx
src/Layers/LayerEntry.jsx

Depends on:
https://github.com/Kitware/itk-vtk-viewer/pull/668
TODO

Add Compare Methods: cyan-magenta and blend

---

package-lock.json
package.json
src/Layers/LayerEntry.jsx

Allow user to draw a bounding box around any of the image layers.

feat(LayerEntry): Toggle bounding box around images

---

.readthedocs.yml

Required recently for ReadTheDocs.

build(docs): add recently required .readthedocs.yml

---

src/Layers/CompareControls.jsx
src/Layers/LayerEntry.jsx
src/Main/PlaneSliders.jsx
src/Main/ViewModeButtons.jsx
src/Main/ViewPlanesToggle.jsx
src/style.css

- "Data visibility" tooltip to "Bounding box" 
- Image Mix row should not be present with single image
- When planes are not visible, do not have plane sliders
- Fix clicking below the sidebar

Interaction fixes

---

index.html
public/compareTest.html
public/index.html
src/Layers/LayerEntry.jsx
src/Layers/LayersInterface.jsx
src/style.css

- Adds working download button.
- All image layers take up whole row to fit all the buttons.

Download volume

---

package-lock.json
package.json
src/Images/TransferFunctionWidget.jsx
src/Images/createTransferFunctionEditor.js

depends on https://github.com/Kitware/itk-vtk-viewer/pull/728

feat: integrate color range transfer function editor
